config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"

  resources :events # This creates ALL the standard routes!
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord

  def self.upcoming
     where("starts_at > ?", Time.now).order("starts_at")
  end

  def free?
    price.blank? || price.zero?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
      @events = Event.upcoming
    end

    def show
      @event = Event.find(params[:id])
    end

    def edit
      @event = Event.find(params[:id])
    end

    def update
      @event = Event.find(params[:id])
      @event.update(event_params)
      redirect_to @event
    end

    def new
      @event = Event.new
    end

    def create
      @event = Event.new(event_params)
      @event.save
      redirect_to @event
    end

    def destroy
      @event = Event.find(params[:id])
      @event.destroy
      redirect_to events_url, status: :see_other
    end

    private

    def event_params
      params.require(:event).permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper

   def price(event)
     if event.free?
       "Free"
     else
       number_to_currency(event.price, precision: 0)
     end
  end

  def day_and_time(event)
    event.starts_at.strftime("%B %d at %I:%M %P")
  end

end

app/views/events/_form.html.erb
<%= form_with(model: event) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 5 %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :starts_at %>
  <%= f.datetime_select :starts_at, {ampm: true}, {class: "datetime"} %>

  <%= f.label :capacity %>
  <%= f.number_field :capacity %>

  <%= f.label :image_file_name %>
  <%= f.text_field :image_file_name %>

  <%= f.submit %>

<% end %>

app/views/events/edit.html.erb
<h1>Editing <%= @event.name %></h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
  <% @events.each do |event|  %>
    <section class="event">
      <div class="image">
        <%= image_tag event.image_file_name %>
      </div>
      <div class="summary">
        <h2><%= link_to event.name, event %></strong>
        <h3><%= day_and_time(event) %> in <%= event.location %></h3>
        <span class="price">
          <%= price(event) %>
        </span>
      <p>
        <%= truncate(event.description, length: 35, separator: ' ') %>
      </p>
    </div>
  </section>
  <% end %>

  <section class="admin">
    <%= link_to "Add New Event", new_event_path, class: "button" %>
  </section>

app/views/events/new.html.erb
<h1>Create a New Event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<section class="event-details">
        <div class="image">
        <%= image_tag @event.image_file_name %>
      </div>

  <div class="details">
    <h1><%= @event.name %></h1>
    <h2> <%= pluralize(@event.capacity, "spot") %> &bull; <%= price(@event) %> </h2>
    <h3> <%= day_and_time(@event) %> in <%= @event.location %> </h3>
    <p>
      <%= @event.description %>
    </p>
  </div>
</section>

<section class="admin">
  <%= link_to "Edit", edit_event_path(@event), class: "button" %>
  <%= link_to "Delete", @event, class: "button", data: { turbo_method: :delete, turbo_confirm: "Really?"} %>
</section>

app/views/layouts/_footer.html.erb
    <footer>
      <p>
        Made in <a href="http://atchity.net">Atchity.net</a>
      </p>
    </footer>

app/views/layouts/_header.html.erb
    <header>
      <nav>
        <%= link_to image_tag("logo.png"), root_path %>
        <ul>
          <li>
            <%= link_to "All Events", events_path %>
          </li>
        </ul>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% AutoprefixerRails.uninstall(Rails.application.assets) %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="content">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>

  </body>
</html>